import type { Metadata } from "next";
import Link from "next/link";
import { articleState, CATALOG_RUNS, catalogForRun } from "@/lib/catalog";
import { featureSlug } from "@/lib/wiki";

export const metadata: Metadata = {
  title: "Types · Signified",
  description:
    "The five kinds of thing the wiki holds: observation, claim, evidence, challenge, and talk.",
};

const NAV = [
  { href: "/blog/types", label: "Types", current: true },
  { href: "/wiki", label: "Articles" },
  { href: "/wiki/method", label: "Method" },
] as const;

const KINDS = [
  {
    id: "observation",
    name: "Observation",
    lead: "What the computer produced on a run: a prompt, a completion, an attribution graph, a measured activation.",
    body: [
      "The Canberra run is the observation this wiki is built around. Gemma 2 2B was given “The capital of Australia is.” It wrote Canberra. circuit-tracer then produced an attribution graph: nodes for prompt tokens, internal features, and the output token, with weights on the paths between them. Feature 18472 sits on a strong path from Australia into that completion. Feature 2201 is louder on the word capital. Feature 3308 writes more strongly into the city name itself. Those are measurements. They are not yet meanings.",
      "An observation can be rich without being decisive. The graph can show which units were active, how strongly they wrote, and which tokens they sat between. It cannot tell you whether 18472 is a geography detector or a capital-city retriever. Attribution is correlational until an intervention has been run. Until then the path is a fact about this completion, not a cause, and not a category.",
    ],
    not: "Not a meaning. A path on the graph is not a cause until an intervention has been run. A public label on the same unit is not an observation either: it is someone else’s reading, filed elsewhere.",
    example:
      "On this run the prompt names a country and asks for a capital. Feature 18472 takes a strong path from the token Australia, a weaker path from capital, and writes into Canberra. That sentence can sit on the page without anyone having to say what the feature “is.”",
  },
  {
    id: "claim",
    name: "Claim",
    lead: "A person’s reading of a feature. It should read as a hypothesis, not a post.",
    body: [
      "A claim is attached to a unit and derived from a run. It has an author. It can be supported, challenged, or left unresolved. The wiki will not complete the sentence “this feature represents…” for you. If nobody writes a reading, the article stays a stub: the graph is still an observation, and that is all.",
      "Alex’s reading of Feature 18472 is the canonical claim on this site: the unit represents Australian geographic entities. On that view it should fire on Sydney and Tasmania as well as Canberra, and stay quiet on words that are not places. The path from Australia is the main exhibit. The word capital in the prompt is incidental. That is a hypothesis about a category. It is not a caption generated by another model, and it is not a fact about the weights.",
    ],
    not: "Not a fact. A human interpretation is not evidence, and neither is a model-generated explanation. A lemma on the article — “Australian geographic entities” — is the claim in short, not the unit’s true name.",
    example:
      "Alex: Feature 18472 represents Australian geographic entities. The article holds that sentence as a claim. Status on the index is contested, because a second reading has been filed. Contested is not failed. It is the honest state of the argument.",
  },
  {
    id: "evidence",
    name: "Evidence",
    lead: "A numerical result from an experiment that was actually run. Notes may accompany the number. They do not replace it.",
    body: [
      "The computer is allowed to produce evidence. A person is not, except by running the test. A contrastive prompt set, an activation rate, a replication, an intervention that silences a node and changes the completion: those are evidence. A paragraph explaining why the number “makes sense” is a note. The note may sit next to the result. It does not become the result.",
      "This is the constraint that keeps the product honest. Do not attach an explanation from another model as evidence. Do not treat a path on the graph as an intervention. Do not let a confident comment in talk migrate into the evidence list because it agrees with the claim. If the experiment was not run, there is no number to store, and the claim stays a claim.",
    ],
    not: "Not an explanation from another model. Not a comment. Not a graph, until someone has intervened. Not a vibe that the reading “fits.”",
    example:
      "A contrast: the feature is active on place names and quiet on matched unrelated nouns. The two rates are the evidence. The story that “this confirms geography” is not. On Feature 4410, one such contrast has been stored and nobody has challenged the reading. Supported is not settled. An uncontested article is still a claim with a number beside it.",
  },
  {
    id: "challenge",
    name: "Challenge",
    lead: "Another reading of the same unit. Both stay on the page. The article does not pick a winner.",
    body: [
      "A challenge is not a deletion of the first claim, and it is not a vote. It is a second hypothesis about the same observation. The two readings have to come apart somewhere: a prompt set, an intervention, a token the first reading needs and the second does not. Until that test is run, both remain, and the article’s job is to keep them visible.",
      "Sam’s reading of Feature 18472 is the canonical challenge: capital-city retrieval, not Australian geography. The prompt is a capital-of frame. A feature that completes Canberra here would also complete Paris, Tokyo, or Oslo in the same frame, and would go quiet on Australian rivers and deserts. Geography, on this view, is a confound. The two claims are not worded differently. They predict different silences.",
    ],
    not: "Not a deletion of the first claim. Not a vote. Not a reputation score. Not a “current consensus.” The page does not average the two readings into a softer third.",
    example:
      "Sam: Feature 18472 is capital-city retrieval. The disagreement is sharpest on prompts that never mention Canberra, and on prompts that mention Australian places without asking for a capital. Those tests have been named. Naming a test is not running it. Until someone does, both readings stay.",
  },
  {
    id: "talk",
    name: "Talk",
    lead: "What people say. A comment can disagree with the article, or bring a public view to the same feature.",
    body: [
      "Talk is stored so the argument has a place that is not the evidence list and not the claim. A reader may point at a Neuronpedia label, a paper, a similar feature on another run, or a hunch that does not yet rise to a second reading. All of that belongs here. None of it is proof. None of it changes the status of the article by itself.",
      "The temptation is to treat a good comment as if it had already done the work of a challenge or an experiment. It has not. If someone wants the public geography label to count against Sam’s retrieval reading, they still have to file a claim or run a test. Talk can point at the work. It cannot stand in for it.",
    ],
    not: "Never proof. Talk does not count as evidence, and a thread of agreement is not a status change. The article can be full of comments and still have no second reading.",
    example:
      "A reader may say the public Neuronpedia label already treats this unit as geography. That belongs in talk, next to the claim, not in the evidence list, and not as an automatic win for Alex. Another reader may say the graph “looks like retrieval.” Same rule. Looks like is talk.",
  },
] as const;

export default function TypesPage() {
  return (
    <div className="blog-grid is-types-page">
      <h1 className="blog-hej">Types</h1>

      <nav className="blog-nav" aria-label="On this page">
        <span className="blog-dot" aria-hidden="true" />
        <ul>
          {NAV.map((item) => (
            <li key={item.href}>
              <Link
                href={item.href}
                aria-current={"current" in item && item.current ? "page" : undefined}
              >
                {item.label}
              </Link>
            </li>
          ))}
        </ul>
        <p className="blog-nav-label">Kinds</p>
        <ul>
          {KINDS.map((kind) => (
            <li key={kind.id}>
              <a href={`#${kind.id}`}>{kind.name}</a>
            </li>
          ))}
        </ul>
        <p className="blog-nav-label">On the page</p>
        <ul>
          <li>
            <a href="#together">Held together</a>
          </li>
        </ul>
        <p className="blog-nav-label">Articles</p>
        {CATALOG_RUNS.map((run) => (
          <div key={run.id}>
            <p className="blog-nav-label">
              {run.modelName} · {run.kicker}
            </p>
            <ul>
              {catalogForRun(run.id).map((item) => {
                const state = articleState(item);
                return (
                  <li key={item.id}>
                    <Link
                      href={`/wiki/${featureSlug(item.id)}`}
                      className={`is-${state}`}
                    >
                      {item.label}
                    </Link>
                  </li>
                );
              })}
            </ul>
          </div>
        ))}
      </nav>

      <div className="blog-copy">
        <p className="blog-dek">
          Five kinds of sentence about the same run. The wiki’s job is to keep
          them from collapsing into each other.
        </p>
        <p>
          Signified is not a better graph renderer, and it is not a model that
          looks at a graph and tells you what a feature means. It is a place
          that holds an evolving epistemic object: an observation, plus the
          interpretations, evidence, and disagreement through which that
          observation is argued over. The five types below are that object,
          taken apart so you can see the joints.
        </p>
        <p>
          Mix the types and the page starts lying. A graph looks like a verdict.
          A comment looks like a test. A caption from another model looks like
          proof. A public label looks like the unit’s real name. Keep them
          apart and the article can stay open: two readings of Feature 18472
          can sit on the same page without the site having to pick a winner,
          and a number can sit next to a claim without turning the claim into a
          fact.
        </p>
        <p>
          You can call this a schema if you want. It is really a way of keeping
          those sentences from collapsing. Observation, claim, evidence,
          challenge, talk. The computer may produce the first and the third. A
          person has to write the others. The loop is observe, interpret, test,
          contest, revise. The types are what those stages are allowed to
          contain.
        </p>

        <ol className="blog-kinds">
          {KINDS.map((kind, index) => (
            <li key={kind.id} id={kind.id} className="blog-kind">
              <p className="blog-kind-num">{String(index + 1).padStart(2, "0")}</p>
              <div>
                <h2>{kind.name}</h2>
                <p>{kind.lead}</p>
                {kind.body.map((paragraph) => (
                  <p key={paragraph.slice(0, 48)}>{paragraph}</p>
                ))}
                <p className="blog-kind-not">{kind.not}</p>
                <p className="blog-kind-ex">
                  <span>On this run.</span> {kind.example}
                </p>
              </div>
            </li>
          ))}
        </ol>

        <section className="blog-close" id="together">
          <h2>Held together</h2>
          <p>
            On an article the types are not a list. They are regions of the
            page, and each region is only allowed to hold one kind of sentence.
          </p>
          <p>
            The left column is the essay: what this feature is doing in the
            argument, not a recap of the graph. Evidence and talk live there,
            under their own headings, so a number and a comment cannot drift
            into the same paragraph and look like the same kind of thing. The
            right column holds the run, the readings, the graph, and a note on
            the selected node. On this run is the observation. Read is the
            claim and its challenge. The graph is still an observation, even
            when you drag a weight. The note is inspection, not a verdict.
          </p>
          <p>
            Status on the index — contested, supported, unresolved, stub —
            follows from which types are present, not from how confident anyone
            sounds. Two readings: contested. One reading and a stored result,
            no challenge: supported. One reading and no contest: unresolved. A
            graph and nobody’s sentence: a stub. The article does not average
            those states. It reports them.
          </p>
          <p>
            Feature 18472 is the worked example. The observation is the
            Canberra completion and the path from Australia. The claim is
            Alex’s geography reading. The challenge is Sam’s retrieval reading.
            Evidence, when it arrives, will be a contrast that those two
            readings cannot both survive. Talk is whatever else people need to
            say in the meantime. That is already a real article. The types are
            how it stays one.
          </p>
        </section>

        <p>
          <Link href="/wiki/feature-18472" className="blog-cta">
            See the types held in one article →
          </Link>
        </p>
      </div>

      <figure className="blog-plate" aria-label="The five types">
        <figcaption>Signified</figcaption>
        <ul>
          {KINDS.map((kind) => (
            <li key={kind.id}>{kind.name}</li>
          ))}
        </ul>
      </figure>
    </div>
  );
}
