import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Types · Signified",
  description:
    "The five kinds of thing the wiki holds: observation, claim, evidence, challenge, and talk.",
};

const NAV = [
  { href: "/blog/types", label: "Types", current: true },
  { href: "/articles", label: "Articles" },
  { href: "/wiki/method", label: "Method" },
] as const;

const KINDS = [
  {
    id: "observation",
    name: "Observation",
    lead: "What the computer produced on a run: a prompt, a completion, an attribution graph, a measured activation.",
    body: [
      "This wiki is built around public sentences and what a model does with them. Gemma 2 2B was given “Georgia is a country in the Caucasus region on the coast of the.” It wrote Black Sea. GPT-OSS 20B was given other leads — Hume, Jung, phlogiston, a thangka — and the Iliad line. Each run has an attribution graph: tokens, internal features, the output. Feature 3102 sits on a strong path from Georgia into that completion. Those are measurements. They are not yet meanings.",
      "An observation can be rich without being decisive. The graph can show which units were active, how strongly they wrote, and which tokens they sat between. It cannot tell you whether 3102 is the Caucasus republic or a name-token that would also complete Atlanta. Attribution is correlational until an intervention has been run. Until then the path is a fact about this completion, not a cause, and not a category.",
    ],
    not: "Not a meaning. A path on the graph is not a cause until an intervention has been run. A public label on the same unit is not an observation either: it is someone else’s reading, filed elsewhere.",
    example:
      "On this run the prompt names Georgia and asks for a coast. Feature 3102 takes a strong path from that name into Black Sea. That sentence can sit on the page without anyone having to say what the feature “is.” Wikipedia’s own gloss of the country belongs in talk.",
  },
  {
    id: "claim",
    name: "Claim",
    lead: "A person’s reading of a feature. It should read as a hypothesis, not a post.",
    body: [
      "A claim is attached to a unit and derived from a run. It has an author. It can be supported, challenged, or left unresolved. The wiki will not complete the sentence “this feature represents…” for you. If nobody writes a reading, the article stays a stub: the graph is still an observation, and that is all.",
      "Alex’s reading of Feature 3102 is a canonical claim on this site: the unit is the historical country — wine, church, the range. On that view it should go quiet on “Georgia is a state in the,” and stay loud on Tbilisi and Kartvelian names. That is a hypothesis about a category. It is not a caption generated by another model, and it is not a fact about the weights.",
    ],
    not: "Not a fact. A human interpretation is not evidence, and neither is a model-generated explanation. A lemma on the article — “Georgia” — is the claim in short, not the unit’s true name.",
    example:
      "Alex: Feature 3102 is the historical country. The article holds that sentence as a claim. Status on the index is contested, because a second reading has been filed. Contested is not failed. It is the honest state of the argument.",
  },
  {
    id: "evidence",
    name: "Evidence",
    lead: "A numerical result from an experiment that was actually run. Notes may accompany the number. They do not replace it.",
    body: [
      "The computer is allowed to produce evidence. A person is not, except by running the test. A contrastive prompt set, an activation rate, a replication, an intervention that silences a node and changes the completion: those are evidence. A paragraph explaining why the number “makes sense” is a note. The note may sit next to the result. It does not become the result.",
      "This is the constraint that keeps the product honest. Do not attach an explanation from another model as evidence. Do not treat a path on the graph as an intervention. Do not let a confident comment in talk migrate into the evidence list because it agrees with the claim. If the experiment was not run, there is no number to store, and the claim stays a claim.",
    ],
    not: "Not an explanation from another model. Not a comment. Not a graph, until someone has intervened. Not a vibe that the reading “fits.”",
    example:
      "A contrast: the feature is active on country-names and quiet on US-state frames. The two rates are the evidence. The story that “this confirms the republic” is not. An uncontested article with a stored number is still a claim. Supported is not settled.",
  },
  {
    id: "challenge",
    name: "Challenge",
    lead: "Another reading of the same unit. Both stay on the page. The article does not pick a winner.",
    body: [
      "A challenge is not a deletion of the first claim, and it is not a vote. It is a second hypothesis about the same observation. The two readings have to come apart somewhere: a prompt set, an intervention, a token the first reading needs and the second does not. Until that test is run, both remain. On the article, that second sentence sits in talk, not beside the first claim in the rail.",
      "Sam’s reading of Feature 3102 is the canonical challenge: a name-token, not the country. The same string completes an American frame with Atlanta. Country, on this view, is one occupant of Georgia, not the category. The two claims are not worded differently. They predict different silences.",
    ],
    not: "Not a deletion of the first claim. Not a vote. Not a reputation score. Not a “current consensus.” The page does not average the two readings into a softer third.",
    example:
      "Sam: Feature 3102 is a name-token. The disagreement is sharpest on “Georgia is a state in the,” and on Kartvelian names that never mention the English word. Those tests have been named. Naming a test is not running it. Until someone does, both readings stay.",
  },
  {
    id: "talk",
    name: "Talk",
    lead: "The other reading of the same unit, and what people say. A contest is not a comment. A comment is not evidence.",
    body: [
      "Talk is where a second reading lives, and where comments sit under it. Sam’s name-token reading of Feature 3102 is a challenge: another hypothesis about the same observation. It belongs here, next to the thread, not in the right-hand rail beside Alex. Both remain. The article does not pick a winner.",
      "A comment can disagree with the article, point at a public label, or bring a hunch that does not yet rise to a reading. None of that is proof. The temptation is to treat a good comment as if it had already done the work of a challenge or an experiment. It has not. Talk can hold the contest and point at the work. It cannot stand in for a test.",
    ],
    not: "Never proof. A second reading is not a deletion of the first, and a thread of agreement is not a status change. The article can be full of comments and still have no contest.",
    example:
      "Sam’s reading sits in talk: Feature 3102 is a name-token. Wikipedia’s gloss of the republic sits under it as a comment, not as evidence, and not as an automatic win for Alex.",
  },
] as const;

export default function TypesPage() {
  return (
    <div className="blog-grid is-types-page">
      <h1 className="blog-hej">Types</h1>

      <nav className="blog-nav" aria-label="On this page">
        <span className="blog-dot" aria-hidden="true" />
        <ul>
          {NAV.map((item) => (
            <li key={item.href}>
              <Link
                href={item.href}
                aria-current={"current" in item && item.current ? "page" : undefined}
              >
                {item.label}
              </Link>
            </li>
          ))}
        </ul>
        <p className="blog-nav-label">Kinds</p>
        <ul>
          {KINDS.map((kind) => (
            <li key={kind.id}>
              <a href={`#${kind.id}`}>{kind.name}</a>
            </li>
          ))}
        </ul>
        <p className="blog-nav-label">On the page</p>
        <ul>
          <li>
            <a href="#together">Held together</a>
          </li>
        </ul>
      </nav>

      <div className="blog-copy">
        <p className="blog-dek">
          Five kinds of sentence about the same run. The wiki’s job is to keep
          them from collapsing into each other.
        </p>
        <p>
          Signified is not a better graph renderer, and it is not a model that
          looks at a graph and tells you what a feature means. It is a place
          that holds an evolving epistemic object: an observation, plus the
          interpretations, evidence, and disagreement through which that
          observation is argued over. The five types below are that object,
          taken apart so you can see the joints.
        </p>
        <p>
          Mix the types and the page starts lying. A graph looks like a verdict.
          A comment looks like a test. A caption from another model looks like
          proof. A public label looks like the unit’s real name. Keep them
          apart and the article can stay open: two readings of Feature 3102
          can sit on the same page without the site having to pick a winner,
          and a number can sit next to a claim without turning the claim into a
          fact.
        </p>
        <p>
          You can call this a schema if you want. It is really a way of keeping
          those sentences from collapsing. Observation, claim, evidence,
          challenge, talk. The computer may produce the first and the third. A
          person has to write the others. The loop is observe, interpret, test,
          contest, revise. The types are what those stages are allowed to
          contain.
        </p>

        <ol className="blog-kinds">
          {KINDS.map((kind, index) => (
            <li key={kind.id} id={kind.id} className="blog-kind">
              <p className="blog-kind-num">{String(index + 1).padStart(2, "0")}</p>
              <div>
                <h2>{kind.name}</h2>
                <p>{kind.lead}</p>
                {kind.body.map((paragraph) => (
                  <p key={paragraph.slice(0, 48)}>{paragraph}</p>
                ))}
                <p className="blog-kind-not">{kind.not}</p>
                <p className="blog-kind-ex">
                  <span>On this run.</span> {kind.example}
                </p>
              </div>
            </li>
          ))}
        </ol>

        <section className="blog-close" id="together">
          <h2>Held together</h2>
          <p>
            On an article the types are not a list. They are regions of the
            page, and each region is only allowed to hold one kind of sentence.
          </p>
          <p>
            The left column is the essay: what this feature is doing in the
            argument, not a recap of the graph. The run sits in the header.
            Alex’s reading, evidence, and talk follow. The graph is first-class
            on the right, with a note on the selected node. Sam’s contest lives
            in talk, then a threaded comment.
          </p>
          <p>
            Status on the index — contested, supported, unresolved, stub —
            follows from which types are present, not from how confident anyone
            sounds. Two readings: contested. One reading and a stored result,
            no challenge: supported. One reading and no contest: unresolved. A
            graph and nobody’s sentence: a stub. The article does not average
            those states. It reports them.
          </p>
          <p>
            Feature 3102 is a worked example. The observation is the Georgia
            completion and the path from the name. The claim is Alex’s country
            reading. The challenge is Sam’s name-token, in talk. Wikipedia’s
            gloss of the republic belongs under that, as a comment. Evidence,
            when it arrives, will be a contrast that those two readings cannot
            both survive. That is already a real article. The types are how it
            stays one.
          </p>
        </section>

        <p>
          <Link href="/wiki/feature-3102" className="blog-cta">
            See the types held in one article →
          </Link>
        </p>
      </div>

      <figure className="blog-plate" aria-label="The five types">
        <figcaption>Signified</figcaption>
        <ul>
          {KINDS.map((kind) => (
            <li key={kind.id}>{kind.name}</li>
          ))}
        </ul>
      </figure>
    </div>
  );
}
